# Generated by Django 5.1.11 on 2025-06-28 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('test_result', 'Test Result'), ('meal_log', 'Meal'), ('sleep_log', 'Sleep'), ('exercise', 'Exercise'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('note', 'Note'), ('goal', 'Goal'), ('visit', 'Doctor Visit'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
