# Generated by Django 5.1.11 on 2025-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timelineevent_created_at_timelineevent_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Optional Tailwind or Lucide icon class (e.g., 'flask', 'apple', 'pill')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='severity',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild Concern'), ('moderate', 'Moderate Concern'), ('high', 'High Risk')], default='normal', help_text='Optional severity label for this event', max_length=20, null=True),
        ),
    ]
