# Generated by Django 5.1.11 on 2025-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timelineevent_icon_class_timelineevent_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('LDL', 'LDL Cholesterol'), ('HDL', 'HDL Cholesterol'), ('TG', 'Triglycerides'), ('GLU', 'Fasting Glucose')], max_length=20)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], max_length=10)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trigger_metric', models.CharField(choices=[('LDL', 'LDL Cholesterol'), ('HDL', 'HDL Cholesterol'), ('TG', 'Triglycerides'), ('GLU', 'Fasting Glucose')], max_length=20)),
                ('condition', models.CharField(help_text='e.g., value > 130', max_length=100)),
                ('message', models.TextField(help_text='What should the reminder say?')),
            ],
        ),
    ]
