# Generated by Django 5.1.11 on 2025-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conditiontag_healthrange_reminderrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='color_tag',
            field=models.CharField(blank=True, help_text='Color for event type', max_length=20, null=True),
        ),
    ]
