# Generated by Django 5.1.11 on 2025-06-28 23:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_features_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('🧪', 'Lab'), ('🥗', 'Nutrition'), ('🤖', 'AI'), ('💊', 'Medication')]}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 1)]], {})}),
        ),
    ]
