# Generated by Django 5.1.11 on 2025-06-28 18:24

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conditiontag_healthrange_reminderrule'),
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtestresult',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.conditiontag'),
        ),
    ]
