# Generated by Django 5.1.11 on 2025-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0002_healthtestresult_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtestresult',
            name='ai_interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthtestresult',
            name='interpretation_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthtestresult',
            name='is_trending_down',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthtestresult',
            name='is_trending_up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthtestresult',
            name='standardized_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
