# Generated by Django 5.1.11 on 2025-07-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_healthtestresult_ai_interpretation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtestresult',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
