# Generated by Django 5.1.11 on 2025-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0004_alter_healthtestresult_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtestresult',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
